-- Own routing graph (layer 1: topology) and user-priority cost (layer 2: ratings).
--
-- Topology: public.osm_ways cut at OSM nodes shared by at least two ways (and at way ends) ->
-- public.routing_edges + public.routing_nodes. Rebuilt rarely, by public.rebuild_routing_graph().
-- Ratings: NOT stored in the edges. public.routing_edge_dims joins edges to segment_scores (refreshed
-- every 2 minutes), and public.find_route() builds the cost of every edge per request from the
-- weights the user picks, so new ratings show up in routes without rebuilding anything.
--
-- Profiles: 'driving-car' and 'cycling-regular'. foot-walking stays with the external engine.
--
-- Cost of an edge = travel time * multiplier, where
--   multiplier = 1 + strength * (max(w) / 3) * sum(w_d * penalty_d) / sum(w_d)
--   penalty_d  = (5 - score_d) / 4        (score 5 = best -> 0, score 1 = worst -> 1)
-- w_d are the user's weights 0..3 for surface, views, safety, traffic, parking. All weights 0 gives
-- multiplier 1, i.e. the fastest route. A single dimension at 3 makes the worst roads cost up to
-- (1 + strength) times their travel time.
-- Edges without ratings use priors from OSM tags (surface/smoothness, lit, road class), else 3.

create table public.routing_edges (
  id bigint generated by default as identity primary key,
  way_id bigint not null,
  source bigint not null,                  -- OSM node id, first point of geom
  target bigint not null,                  -- OSM node id, last point of geom
  highway text not null,
  surface text,
  smoothness text,
  lit boolean,
  car_dir text not null check (car_dir in ('both', 'forward', 'backward', 'none')),
  bike_dir text not null check (bike_dir in ('both', 'forward', 'backward', 'none')),
  car_speed_kmh smallint,
  bike_speed_kmh smallint,
  length_m real not null,
  segment_id integer references public.segments (id) on delete set null,  -- rated segment nearest to the edge middle
  geom extensions.geometry(LineString, 4326) not null  -- along the way direction (forward = source -> target)
);
create index routing_edges_geom_idx on public.routing_edges using gist (geom);
create index routing_edges_segment_idx on public.routing_edges (segment_id);
create index routing_edges_way_idx on public.routing_edges (way_id);
create index routing_edges_source_idx on public.routing_edges (source);
create index routing_edges_target_idx on public.routing_edges (target);

create table public.routing_nodes (
  id bigint primary key,                   -- OSM node id
  geom extensions.geometry(Point, 4326) not null,
  car_main boolean not null default false, -- in the largest strongly connected component for cars
  bike_main boolean not null default false
);
create index routing_nodes_car_idx on public.routing_nodes using gist (geom) where car_main;
create index routing_nodes_bike_idx on public.routing_nodes using gist (geom) where bike_main;

-- Internal data: no access through the public API.
alter table public.routing_edges enable row level security;
alter table public.routing_nodes enable row level security;
revoke all on public.routing_edges, public.routing_nodes from anon, authenticated;

-- ---------------------------------------------------------------------------------------------
-- Priors from OSM tags for edges nobody has rated (scale 1..5, 5 = best; null = no opinion).
-- ---------------------------------------------------------------------------------------------

create function public.routing_prior_surface(p_surface text, p_smoothness text)
returns real
language sql immutable parallel safe
set search_path = ''
as $$
  select coalesce(
    case p_smoothness
      when 'excellent' then 5 when 'good' then 4 when 'intermediate' then 3 when 'bad' then 2
      when 'very_bad' then 1 when 'horrible' then 1 when 'very_horrible' then 1 when 'impassable' then 1
    end,
    case p_surface
      when 'asphalt' then 4 when 'concrete' then 4 when 'paved' then 4 when 'paving_stones' then 3
      when 'concrete:plates' then 3 when 'compacted' then 3 when 'fine_gravel' then 2.5
      when 'sett' then 2 when 'cobblestone' then 2 when 'gravel' then 2 when 'ground' then 2
      when 'dirt' then 2 when 'unpaved' then 2 when 'grass' then 1.5 when 'sand' then 1.5
    end
  )::real
$$;

create function public.routing_prior_safety(p_lit boolean)
returns real
language sql immutable parallel safe
set search_path = ''
as $$
  select case p_lit when true then 3.5 when false then 2.5 end::real
$$;

create function public.routing_prior_traffic(p_highway text)
returns real
language sql immutable parallel safe
set search_path = ''
as $$
  select case p_highway
    when 'primary' then 2 when 'primary_link' then 2 when 'secondary' then 2.5 when 'secondary_link' then 2.5
    when 'tertiary' then 3 when 'tertiary_link' then 3 when 'unclassified' then 4 when 'residential' then 4
    when 'living_street' then 4.5 when 'service' then 4 when 'track' then 4.5
    when 'cycleway' then 5 when 'path' then 5 when 'footway' then 5 when 'pedestrian' then 5
    else 3
  end::real
$$;

-- Scores of every edge as the router sees them: ratings (segment_scores) first, then priors, then 3.
create view public.routing_edge_dims with (security_invoker = true) as
select e.id as edge_id,
  coalesce(ss.surface, public.routing_prior_surface(e.surface, e.smoothness), 3)::real as surface,
  coalesce(ss.views, 3)::real as views,
  coalesce(ss.safety, public.routing_prior_safety(e.lit), 3)::real as safety,
  coalesce(ss.traffic, public.routing_prior_traffic(e.highway), 3)::real as traffic,
  coalesce(ss.parking, 3)::real as parking,
  (ss.segment_id is not null) as rated
from public.routing_edges e
left join public.segment_scores ss on ss.segment_id = e.segment_id;
revoke all on public.routing_edge_dims from anon, authenticated;

-- ---------------------------------------------------------------------------------------------
-- Topology build. Run after loading/refreshing osm_ways (and after rebuilding segments).
-- ---------------------------------------------------------------------------------------------

create function public.rebuild_routing_graph()
returns table (edges bigint, nodes bigint, car_main_share numeric, bike_main_share numeric)
language plpgsql
set search_path = public, extensions
as $$
declare
  v_profile text;
begin
  perform set_config('statement_timeout', '0', true);
  truncate public.routing_edges restart identity;
  truncate public.routing_nodes;

  insert into public.routing_edges
    (way_id, source, target, highway, surface, smoothness, lit, car_dir, bike_dir,
     car_speed_kmh, bike_speed_kmh, length_m, geom)
  with pts as (
    select w.way_id, u.node_id, u.n
    from public.osm_ways w, unnest(w.node_ids) with ordinality as u(node_id, n)
  ), junction as (
    select node_id from pts group by node_id having count(distinct way_id) > 1
  ), cuts as (
    select p.way_id, p.n, p.node_id
    from pts p
    join public.osm_ways w on w.way_id = p.way_id
    where p.n = 1 or p.n = cardinality(w.node_ids) or p.node_id in (select node_id from junction)
  ), pairs as (
    select way_id, node_id as source, n as n1,
      lead(node_id) over (partition by way_id order by n) as target,
      lead(n) over (partition by way_id order by n) as n2
    from cuts
  )
  select w.way_id, p.source, p.target, w.highway, w.surface, w.smoothness, w.lit, w.car_dir, w.bike_dir,
    w.car_speed_kmh, w.bike_speed_kmh,
    st_length(g.geom::geography)::real, g.geom
  from pairs p
  join public.osm_ways w on w.way_id = p.way_id
  cross join lateral (
    select st_makeline(array_agg(st_pointn(w.geom, i) order by i)) as geom
    from generate_series(p.n1::integer, p.n2::integer) as i
  ) g
  where p.target is not null and p.source <> p.target and (w.car_dir <> 'none' or w.bike_dir <> 'none');

  update public.routing_edges e
  set segment_id = (
    select s.id from public.segments s
    where s.osm_way_id = e.way_id
    order by s.geom <-> st_lineinterpolatepoint(e.geom, 0.5)
    limit 1
  );

  insert into public.routing_nodes (id, geom)
  select distinct on (id) id, geom from (
    select source as id, st_startpoint(geom) as geom from public.routing_edges
    union all
    select target, st_endpoint(geom) from public.routing_edges
  ) x;

  -- Largest strongly connected component per profile: the nodes find_route() may snap to.
  foreach v_profile in array array['car', 'bike'] loop
    execute format($q$
      update public.routing_nodes n set %1$s_main = true
      where n.id in (
        with comp as (
          select * from extensions.pgr_strongcomponents(
            'select id, source, target,
               case when %1$s_dir in (''both'', ''forward'') then 1 else -1 end as cost,
               case when %1$s_dir in (''both'', ''backward'') then 1 else -1 end as reverse_cost
             from public.routing_edges where %1$s_dir <> ''none'''
          )
        ), big as (
          select component from comp group by component order by count(*) desc limit 1
        )
        select node from comp where component in (select component from big)
      )$q$, v_profile);
  end loop;

  analyze public.routing_edges;
  analyze public.routing_nodes;

  return query
  select (select count(*) from public.routing_edges),
    (select count(*) from public.routing_nodes),
    round((100 * coalesce(sum(e.length_m) filter (where e.car_dir <> 'none' and sn.car_main), 0)
      / nullif(sum(e.length_m) filter (where e.car_dir <> 'none'), 0))::numeric, 1),
    round((100 * coalesce(sum(e.length_m) filter (where e.bike_dir <> 'none' and sn.bike_main), 0)
      / nullif(sum(e.length_m) filter (where e.bike_dir <> 'none'), 0))::numeric, 1)
  from public.routing_edges e
  join public.routing_nodes sn on sn.id = e.source;
end;
$$;
revoke execute on function public.rebuild_routing_graph() from public, anon, authenticated;

-- ---------------------------------------------------------------------------------------------
-- Route search: the cheapest path for the user's priorities, edge by edge.
-- ---------------------------------------------------------------------------------------------

create function public.find_route(
  p_profile text,
  p_from_lon double precision, p_from_lat double precision,
  p_to_lon double precision, p_to_lat double precision,
  p_w_surface integer default 0, p_w_views integer default 0, p_w_safety integer default 0,
  p_w_traffic integer default 0, p_w_parking integer default 0,
  p_strength double precision default null   -- null: 8 for cars, 3 for bikes
)
returns table (
  seq integer, edge_id bigint, way_id bigint, segment_id integer, forward boolean,
  length_m real, time_s double precision,
  surface real, views real, safety real, traffic real, parking real, rated boolean,
  geom extensions.geometry(LineString, 4326)
)
language plpgsql stable
set search_path = public, extensions
as $$
declare
  v_pf text;
  v_default_speed integer;
  w_s integer := greatest(0, least(3, coalesce(p_w_surface, 0)));
  w_v integer := greatest(0, least(3, coalesce(p_w_views, 0)));
  w_f integer := greatest(0, least(3, coalesce(p_w_safety, 0)));
  w_t integer := greatest(0, least(3, coalesce(p_w_traffic, 0)));
  w_p integer := greatest(0, least(3, coalesce(p_w_parking, 0)));
  v_wsum integer;
  v_wmax integer;
  v_mult text;
  v_src bigint;
  v_dst bigint;
  v_from extensions.geometry := st_setsrid(st_makepoint(p_from_lon, p_from_lat), 4326);
  v_to extensions.geometry := st_setsrid(st_makepoint(p_to_lon, p_to_lat), 4326);
  v_margin double precision;
  v_sql text;
  v_attempt integer;
  v_strength double precision;
begin
  -- Cars: speed differences between road classes are large, so ratings need a stronger pull.
  if p_profile = 'driving-car' then v_pf := 'car'; v_default_speed := 30; v_strength := coalesce(p_strength, 8);
  elsif p_profile = 'cycling-regular' then v_pf := 'bike'; v_default_speed := 15; v_strength := coalesce(p_strength, 3);
  else raise exception 'unsupported profile: %', p_profile using errcode = '22023';
  end if;

  v_wsum := w_s + w_v + w_f + w_t + w_p;
  v_wmax := greatest(w_s, w_v, w_f, w_t, w_p);
  if v_wsum = 0 then
    v_mult := '1.0';
  else
    v_mult := format(
      '(1 + %s::float8 * %s::float8 * (%s * greatest(0, least(1, (5 - d.surface) / 4.0)) + %s * greatest(0, least(1, (5 - d.views) / 4.0))'
      ' + %s * greatest(0, least(1, (5 - d.safety) / 4.0)) + %s * greatest(0, least(1, (5 - d.traffic) / 4.0))'
      ' + %s * greatest(0, least(1, (5 - d.parking) / 4.0))) / %s::float8)',
      v_strength, v_wmax / 3.0, w_s, w_v, w_f, w_t, w_p, v_wsum);
  end if;

  execute format(
    'select id from public.routing_nodes where %s_main order by geom <-> $1 limit 1', v_pf)
    into v_src using v_from;
  execute format(
    'select id from public.routing_nodes where %s_main order by geom <-> $1 limit 1', v_pf)
    into v_dst using v_to;
  if v_src is null or v_dst is null or v_src = v_dst then
    return;
  end if;

  v_margin := greatest(0.015, 0.5 * greatest(abs(p_from_lon - p_to_lon), abs(p_from_lat - p_to_lat)));

  -- Attempt 1 searches a corridor around the two points (fast); attempt 2 the whole network.
  for v_attempt in 1..2 loop
    v_sql := format(
      'select e.id, e.source, e.target,
         case when e.%1$s_dir in (''both'', ''forward'')
           then e.length_m / (greatest(coalesce(e.%1$s_speed_kmh, %2$s), 5) / 3.6) * %3$s else -1 end as cost,
         case when e.%1$s_dir in (''both'', ''backward'')
           then e.length_m / (greatest(coalesce(e.%1$s_speed_kmh, %2$s), 5) / 3.6) * %3$s else -1 end as reverse_cost
       from public.routing_edges e
       join public.routing_edge_dims d on d.edge_id = e.id
       where e.%1$s_dir <> ''none'' %4$s',
      v_pf, v_default_speed, v_mult,
      case when v_attempt = 1 then format(
        'and e.geom && st_makeenvelope(%s, %s, %s, %s, 4326)',
        least(p_from_lon, p_to_lon) - v_margin, least(p_from_lat, p_to_lat) - v_margin,
        greatest(p_from_lon, p_to_lon) + v_margin, greatest(p_from_lat, p_to_lat) + v_margin)
      else '' end);

    return query
    select r.path_seq::integer, e.id, e.way_id, e.segment_id, (r.node = e.source),
      e.length_m,
      e.length_m / (greatest(coalesce(case when v_pf = 'car' then e.car_speed_kmh else e.bike_speed_kmh end,
                                      v_default_speed), 5) / 3.6),
      d.surface, d.views, d.safety, d.traffic, d.parking, d.rated,
      case when r.node = e.source then e.geom else st_reverse(e.geom) end
    from extensions.pgr_dijkstra(v_sql, v_src, v_dst, true) r
    join public.routing_edges e on e.id = r.edge
    join public.routing_edge_dims d on d.edge_id = e.id
    where r.edge <> -1
    order by r.path_seq;

    if found then
      return;
    end if;
  end loop;
end;
$$;
revoke execute on function public.find_route(text, double precision, double precision, double precision, double precision,
  integer, integer, integer, integer, integer, double precision) from public, anon, authenticated;
