-- Segment groups: consecutive pieces of one street (about 500 m) that users rate together.
-- OSM cuts roads at every junction, so half of the segments are shorter than 100 m. Segment ids
-- and ratings stay untouched; groups only add a layer on top. Data: supabase/seed/groups_*.sql,
-- generated by scripts/build_segment_groups.py.

create table public.segment_groups (
  id integer primary key,
  name text,
  highway text not null,
  length_m real not null check (length_m > 0),
  segments_count integer not null check (segments_count > 0),
  from_street text,   -- most important other street where the group starts
  to_street text      -- ... and where it ends
);

alter table public.segments
  add column group_id integer references public.segment_groups (id) on delete set null;
create index segments_group_idx on public.segments (group_id);

alter table public.segment_groups enable row level security;
revoke insert, update, delete, truncate on public.segment_groups from anon, authenticated;
create policy "segment_groups: public read" on public.segment_groups
  for select to anon, authenticated using (true);
