-- Core tables. All geometries use SRID 4326, coordinates are [lon, lat].

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null,
  created_at timestamptz not null default now()
);

-- Create a profile row for every new auth user.
create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
      split_part(new.email, '@', 1),
      'user'
    )
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create table public.segments (
  id integer generated by default as identity primary key,
  osm_way_id bigint not null,
  name text,
  highway text not null,
  surface_osm text,
  smoothness_osm text,
  maxspeed integer,
  lit boolean,
  geom extensions.geometry(LineString, 4326) not null,
  length_m real not null check (length_m > 0)
);
create index segments_geom_idx on public.segments using gist (geom);
create index segments_osm_way_id_idx on public.segments (osm_way_id);

create table public.ratings (
  id uuid primary key default gen_random_uuid(),
  segment_id integer not null references public.segments (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  surface smallint check (surface between 1 and 5),
  views smallint check (views between 1 and 5),
  safety smallint check (safety between 1 and 5),
  traffic smallint check (traffic between 1 and 5),
  parking smallint check (parking between 1 and 5),
  time_of_day public.time_of_day not null,
  -- Calendar day in Warsaw time; backend upserts on (user_id, segment_id, rated_on).
  rated_on date not null default ((now() at time zone 'Europe/Warsaw')::date),
  created_at timestamptz not null default now(),
  constraint ratings_has_dimension check (
    num_nonnulls(surface, views, safety, traffic, parking) >= 1
  ),
  constraint ratings_one_per_day unique (user_id, segment_id, rated_on)
);
create index ratings_segment_idx on public.ratings (segment_id);

create table public.comments (
  id uuid primary key default gen_random_uuid(),
  segment_id integer not null references public.segments (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  text text not null check (char_length(text) between 1 and 1000),
  status public.content_status not null default 'visible',
  created_at timestamptz not null default now()
);
create index comments_segment_created_idx on public.comments (segment_id, created_at desc);

create table public.obstacles (
  id uuid primary key default gen_random_uuid(),
  segment_id integer references public.segments (id) on delete set null,
  type public.obstacle_type not null,
  description text check (char_length(description) <= 500),
  geom extensions.geometry(Point, 4326) not null,
  reported_by uuid not null references public.profiles (id) on delete cascade,
  valid_until timestamptz,  -- null = until revoked
  created_at timestamptz not null default now()
);
create index obstacles_geom_idx on public.obstacles using gist (geom);
create index obstacles_segment_idx on public.obstacles (segment_id);

create table public.parking_spots (
  id integer generated by default as identity primary key,
  osm_id bigint not null unique,
  name text,
  capacity integer check (capacity >= 0),
  fee boolean,
  geom extensions.geometry(Point, 4326) not null
);
create index parking_spots_geom_idx on public.parking_spots using gist (geom);

create table public.segment_photos (
  id uuid primary key default gen_random_uuid(),
  segment_id integer not null references public.segments (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  storage_path text not null,        -- object path in bucket segment-photos
  thumbnail_path text not null,      -- thumbnail object path in the same bucket
  taken_at timestamptz,
  status public.content_status not null default 'visible',
  ai_surface jsonb,                  -- optional result of /analyze-surface
  created_at timestamptz not null default now()
);
create index segment_photos_segment_idx on public.segment_photos (segment_id, created_at desc);

create table public.segment_summaries (
  segment_id integer primary key references public.segments (id) on delete cascade,
  summary jsonb not null,            -- Summary from CONTRACT.md without updated_at
  comments_count integer not null,
  model text not null,
  updated_at timestamptz not null default now()
);
